20230330
Tags: #lecture 

# Main:

## Assertations

Все ошибки “происходят” на моменте формирования .exe.

```c++
#include <assert>

int main(){
	assert(2+2==4);
	assert(2+2==5);
}
// main.c: "2+2==5" failed

----------------------------------------------------------------------------------------

static_assert(sizeof(int) ==4,"int must be 4b");

----------------------------------------------------------------------------------------

template <class T>
struct ds {
	
	static_assert(std::is_default_constructable<T>::value,"No constructor");
	
}

struct MyT{
	MyT()=delete;
}

int main(){
	ds<MyT> x;
}

----------------------------------------------------------------------------------------

```

## Коды возврата

(старая школа)

```c++
size_t MyWrite(const MyT* b,size_t k, FILE* f){
	cout << "error";   X (нельзя делать так)
}

int main(){
	int k =5;
if (MyT(...,k,...)!=k){
		(пусть функция возвращает сколько было обработано (т.е. "все ли К записалось"))
	}
}

----------------------------------------------------------------------------------------

FILE* f =fopen("Test.txt","r");
if(f)...
if(!f)...
if(fprintf(f,"...")<0);
```

Try/catch

```c++
try{ //небезопасный код
	
}

catch(){ //реакция на ошибки из try-я

}

----------------------------------------------------------------------------------------

#include <exception>

class exception{
	public:
		exception() noexcept;
		
		exception(const exeption& ) noexcept;

		exception& operation();
		
		virtual~exception();
		virtual const char* what() const noexcept;
}

void fun(){
	if (x==3) throw exeption();
	if (x==4) throw Myex("включи принтер");	
	if (x==5) throw 25;
	if (x==6) throw "?";
}

int main(){
	try{
		fun();
	}
	catch(Myex& e){
		cout <<e.what();
	}
	catch(exception& e){
		cout << e.what();
	}
	catch(int& e){
		cout << e;
	}
	catch(...){
		cout << "error";
	}
}

class Myex: public exception{
	private:
		char* s
	public:
		Myex(char* _s){
			strcpy(s,_s);
	}

	const char* what() const noexcept{
		return s;
	}
}

```

## Exceptions

Exceptions in std:

-   runtime_error:
    -   overtimeflow_error
    -   underflow_error
-   logic_error
    -   invalid_argument
    -   length_error
    -   out_of_range
-   bad_alloc
-   bad_cast
-   bad_time_id
-   bad_exception

***Links:*** [[00 Lections]]